version: '3'

services:

  tomcat:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: "${HOST_UID}"
        HOST_GID: "${HOST_GID}"
    ports:
      - "8080:8080"
      - "8009:8009"
    tmpfs:
      - /usr/local/tomcat/logs  # disabled by default: STDOUT/STDERR only!
      - /usr/local/tomcat/temp
      - /usr/local/tomcat/work
      - /usr/local/tomcat/conf/Catalina
