version: '3'

services:

  solr:
    container_name: solr
    restart: always
    build:
      context: .
      args:
        HOST_UID: "${HOST_UID:-1000}"
        HOST_GID: "${HOST_GID:-1000}"
        SOLR_CORE: "${SOLR_CORE:-default}"
    ports:
      - "8983:8983"
    tmpfs:
      - /var/solr
      - /opt/solr/server/logs  # disabled by default: STDOUT/STDERR only!
    volumes:
      - "data:/opt/solr/server/solr/${SOLR_CORE:-default}"
    environment:
      - SOLR_HOME=/opt/solr/server/solr
      - LOG4J_PROPS=/opt/solr/server/solr/log4j.properties
      - SOLR_PID_DIR=/var/solr

volumes:
  data: {}